language: cpp
compiler:
   - gcc
before_install:
   - sudo apt-get update
notifications:
  recipients:
    - kbesrv@gmail.com
  email:
    on_success: change
    on_failure: always
script: cd kbe/src && make